---
- name: Playbook to generate hwreport
  hosts: all
  tasks:
    - name: TASK - Downloading template
      ansible.builtin.get_url:
        url: http://10.10.1.200/materials/emptyhw.report
        dest: /root/hwreport.txt
        owner: root
        group: root
        mode: '0644'
    - name: TASK - Generating hwreport
      ansible.builtin.replace:
        path: /root/hwreport.txt
        regexp: "{{ item.key }}"
        replace: "{{ item.value }}"
      loop:
        - key: inventory hostname
          value: "{{ ansible_facts['hostname'] }}"
        - key: memory in MB
          value: "{{ ansible_facts['memtotal_mb'] }}"
        - key: BIOS_version
          value: "{{ ansible_facts['bios_version'] }}"
        - key: disk_sda_size
          value: "{{ ansible_facts['devices']['vda']['size'] | default('NONE') }}"
        - key: disk_sdb_size
          value: "{{ ansible_facts['devices']['vdb']['size'] | default('NONE') }}"
