---
- name: Playbook to Create partition and lvm for other plays
  hosts: "{{ HOSTS }}"
  gather_facts: true
  become: true
  tasks:
    - name: Task-1 Creating Partition
      community.general.parted:
        device: /dev/vdb
        number: 1
        part_type: primary
        part_end: "1000MB"
        state: present
      when: ansible_facts['devices']['vdb']['partitions'] | length == 0
      register: part_info

    - name: Task-2 Creating VolumeGroup
      community.general.lvg:
        pvs: /dev/vdb1
        vg: research
        state: present
      when: part_info is not skipped or ansible_facts['devices']['vdb']['partitions']['vdb1'] is defined

    - name: Task-3 Creating LogicalVolume
      community.general.lvol:
        vg: research
        lv: research_lv
        state: present
        size: 512M
        active: true
      

