---
- name: Playbook-1 Managing php-mariadb
  hosts: dev,test,prod
  tasks:
    - name: TASK - installing php-mariadb
      ansible.builtin.dnf:
        name:
          - php
          - mariadb
        state: present

- name: Playbook-2 Managing RPM Development Tools
  hosts: test
  tasks:
    - name: TASK - installing RPM Development Tools
      ansible.builtin.dnf:
        name: "@RPM Development Tools"
        state: present

- name: Playbook-3 Managing package upgrade
  hosts: prod
  tasks:
    - name: TASK - upgrading packages
      ansible.builtin.dnf:
        name: "*"
        state: latest


