---
- name: Playbook to configure repositories
  hosts: all
  tasks:
    - name: TASK - Importing rpm-gpg key
      ansible.builtin.rpm_key:
        key: http://10.10.1.200/alma10/RPM-GPG-KEY-AlmaLinux-10
        state: present
    - name: TASK - Configuring base repository
      ansible.builtin.yum_repository:
        file: ex294_repo
        state: present
        name: EX294_BASE
        description: EX294 base software
        baseurl: http://10.10.1.200/alma10/BaseOS
        enabled: true
        gpgcheck: true
        gpgkey: http://10.10.1.200/alma10/RPM-GPG-KEY-AlmaLinux-10

    - name: TASK - Configuring stream repository
      ansible.builtin.yum_repository:
        file: ex294_repo
        state: present
        name: EX294_STREAM
        description: EX294 stream software
        baseurl: http://10.10.1.200/alma10/AppStream
        enabled: true
        gpgcheck: true
        gpgkey: http://10.10.1.200/alma10/RPM-GPG-KEY-AlmaLinux-10

