---

- name: Install proxy and firewall packages
  ansible.builtin.dnf:
    name: [haproxy, firewalld]
    state: present

- name: Ensure webserver facts are available in hostvars memory
  ansible.builtin.setup:
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['webservers'] }}"
  when: hostvars[item]['ansible_default_ipv4'] is undefined

- name: Deploy dynamic HAProxy configuration
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'

- name: Start HAProxy and firewall daemons
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: [haproxy, firewalld]

- name: Open HTTP load balancer ports
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true
